# Generated by Django 4.2.6 on 2025-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdetails_age_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='token',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
