# Generated by Django 4.2.6 on 2025-07-06 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdetails_token_alter_userdetails_profile_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot be more than 150')]),
        ),
    ]
