# Generated by Django 4.2.6 on 2025-07-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactiondetails_manual'),
    ]

    operations = [
        # Drop the existing table
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_transactiondetails CASCADE;",
            reverse_sql=""
        ),
        # Recreate the table with correct foreign key
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('transaction_type', models.CharField(max_length=8, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund')])),
                ('description', models.CharField(max_length=255, blank=True, null=True)),
                ('category', models.CharField(max_length=100, blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(max_length=20, blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='api.userdetails', to_field='user_id')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Transaction Details',
            },
        ),
    ]
